### ISSUE TITLE
Error in keysort.js

### ISSUE THREAD

**Issue by olofweb** [avoidwork/keysort#3]
Sorry if my message is off topic because I'm new to Javascript. 

I try to use your library (keysort.js). I installed laster npm version (1.0.1) but I get this error :

`Uncaught TypeError: Cannot set property 'keysort' of undefined`

I see that the last line of keysort.js is :

`})(undefined);`

If I change this to :

`})(this);`

I don't get the error.

What is the problem ?

Thank you

**Comment by avoidwork** [comment]
Hi,

What version of node are you using?

![screen shot 2017-02-23 at 6 30 47 am](https://cloud.githubusercontent.com/assets/369698/23257406/a3bf6a8c-f991-11e6-807a-4a22849623e6.png)

**Comment by avoidwork** [comment]
Hi,

The IFFE argument `this` can be problematic depending on the env, so I've made it browser/node aware.

**Comment by olofweb** [comment]
Thank you for the patch, now it works. And thank you for the explanation :)
